name: kiranSonarTry_demo
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world1!
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world2!
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world3!
